### ISSUE TITLE
This doesn't make any effect on KDE Neon

### ISSUE THREAD

**Issue by Not-Qualified** [ChrisTitusTech/Top-5-Bootloader-Themes#1]
I've run all things and it's showing that all things done properly though not affect boot loader, it's showing KDE Neon's by default boot loader screen
 
And, By the Way, Chris - You are rocking

Screenshot of Process :

![bootloader_problem_kde_neon](https://user-images.githubusercontent.com/52353116/110237522-892ecb80-7f62-11eb-9c16-e2a32d7fc7d4.png)

**Comment by TangoMan75** [comment]
Unfortunately custom theme doesn't show on Ubuntu bootloader either.

Can you screenshot the content of your grub file ?

```
cat /etc/default/grub
```

![Screenshot from 2021-03-08 09-10-50](https://user-images.githubusercontent.com/14804833/110293094-68ac5300-7fee-11eb-99c3-215f3b7b0fe1.png)

**Comment by Not-Qualified** [comment]
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""


GRUB_THEME="/usr/share/grub/themes/fallout/theme.txt"

**Comment by TangoMan75** [comment]
I see now where my bug was coming from : GRUB_THEME="/usr/share/grub/themes//theme.txt"

@Not-Qualified  : You need to change `GRUB_TIMEOUT_STYLE=hidden` with `GRUB_TIMEOUT_STYLE=menu` and set `GRUB_TIMEOUT=0` to something else like `GRUB_TIMEOUT=10`

My version of the script does it automatically, use it if you don't feel like waiting for Chris to merge my PR.

@ChrisTitusTech I believe you can close this Issue now

**Comment by Not-Qualified** [comment]
It's not working even after making all the modification as per your suggestion
