### ISSUE TITLE
Nothing Happens in Fedora.

### ISSUE THREAD

**Issue by pakosaan** [ChrisTitusTech/Top-5-Bootloader-Themes#10]
What the Tiltle says.

**Comment by kralti** [comment]
You need to
sudo nano /etc/default/grub
and then comment out the line 
GRUB_TERMINAL_OUTPUT
run the install script

**Comment by rafay99-epic** [comment]
> You need to sudo nano /etc/default/grub and then comment out the line GRUB_TERMINAL_OUTPUT run the install script

@kralti Thank you, brother, I have been searching for the solution for a while, like for the last 3 weeks, but thanks to you, I have solved the problem. Thank you so much,
