### ISSUE TITLE
not working on fedora 36

### ISSUE THREAD

**Issue by FediHajjej** [ChrisTitusTech/Top-5-Bootloader-Themes#9]
hi i tried the CyberRE GRUB theme on fedora 36 but it doesn't seem to change anything the bash script says everything is fine but when i reboot i see no theme this used to work on fedora 35

**Comment by ChrisTitusTech** [comment]
That is because fedora 36 doesn't use grub.

**Comment by Griffen8280** [comment]
I got themes working on my Fedora 36, including these.  Here is how:
After you clone this repository you will need to manually copy the theme folder you want to the boot location
`sudo cp -R Vimix /boot/grub2/themes/`

Next you'll need to edit your primary Grub config generation file
`sudo nano /etc/default/grub`  _I like using nano_

In this file make it look like this
`GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"`
`GRUB_DEFAULT=saved`
`GRUB_DISABLE_SUBMENU=true`
`GRUB_CMDLINE_LINUX="rhgb quiet selinux=0"`
`GRUB_DISABLE_RECOVERY="true"`
`GRUB_ENABLE_BLSCFG=true`
`GRUB_TIMEOUT_STYLE="menu"`
`GRUB_TIMEOUT="10"`
`GRUB_THEME="/boot/grub2/themes/Vimix/theme.txt"`
`GRUB_GFXMODE=1920x1080,auto`

Finally, and this is the most important part, execute the following command
`sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg` _Mine is a UEFI system_

This will generate the following output on the terminal if everything goes well (or something similar)
> Generating grub configuration file ...
> Found theme: /boot/grub2/themes/Vimix/theme.txt
> Found Windows Boot Manager on /dev/nvme1n1p1@/efi/Microsoft/Boot/bootmgfw.efi
> Adding boot menu entry for UEFI Firmware Settings ...
> done

Reboot and profit!

**Comment by ChrisTitusTech** [comment]
Went ahead and fixed this with a PR #8 
It now works on Fedora 36
